#!/bin/bash

#   What is the sample list of raw samples?
RAW_SAMPLES=

#   Where are we storing the output files?
OUT_DIR=

#   Name this project
PROJECT=

#   What email should we use for job notifications?
EMAIL=user@example.com

#   What is the platform used for sequencing?
PLATFORM=

#   What reference genome are we using?
REF_GEN=

############################################
##########   Quality_Assessment   ##########
############################################

#   What are our QSub settings for Quality_Assessment?
#       Below are the recommended settings
QC_QSUB="mem=4000mb,nodes=1:ppn=4,walltime=6:00:00"

############################################
##########     Read_Depths        ##########
############################################

#   What are our QSub settings for Read_Depths?
#       Below are the recommended settings
RD_QSUB=""

#   Where is the list of FastQC zipfiles?
ZIP_FILES=${OUT_DIR}/Quality_Assessment/${PROJECT}_FastQC_ZipFiles.txt

#   What is the target size, or size of the genome/region that was sequenced?
TARGET=

############################################
##########     Quality_Trimming   ##########
############################################

#   How are forward samples named?
#       Example: _1_sequence.txt.gz
FORWARD_NAMING=

#   How are reverse samples named?
#       Example: _2_sequence.txt.gz
REVERSE_NAMING=

#   What is Scythe's prior?
PRIOR=

#   What is the threshold for trimming?
#       Normal trimming: use 20
#       No trimming based on quality: use 0
THRESHOLD=

############################################
##########  read_mapping_start    ##########
############################################

#   Are we indexing the reference or mapping our samples?
#       Choose from 'map' or 'index'
SUBROUTINE=map

#   Where is our list of trimmed samples?
TRIMMED_LIST=

#   How are trimmed forward samples named?
#       If using the Quality_Trimming portion of the pipeline
#       this should be '_R1_trimmed.fq.gz'
FORWARD_TRIMMED=_R1_trimmed.fq.gz

#   How are trimmed reverse samples named?
#       If using the Quality_Trimming portion of the pipeline
#       this should be '_R2_trimmed.fq.gz'
REVERSE_TRIMMED=_R2_trimmed.fq.gz

#   BWA mem parameters; below are the defaults for BWA mem
#       How many threads are we using?
THREADS=1

#       What is our minimum seed length?
SEED=19

#       What is the band width?
WIDTH=100

#       What is our off-diagonal x-dropoff (Z-dropoff)?
DROPOFF=100

#       What is our re-seed value?
RE_SEED=1.5

#       What is our cutoff value?
CUTOFF=10000

#       Are we in paired-end mode?
PAIRED=true

#       What is our matching score?
MATCH=1

#       What is our mismatch penalty?
MISMATCH=4

#       What is our gap penalty?
GAP=6

#       What is our gap extension penalty?
EXTENSION=1

#       What is our clipping penalty?
CLIP=6

#       What is our unpaired read penatly?
UNPAIRED=9

#       Do we assume the first input query is interleaved?
INTERLEAVED=false

#       Are wewe adding a read group header? Add in final script
#READ_GROUP=

#       What is our minimum threshold?
THRESHOLD=30

#       Do we output all alignments, and mark as secondary?
SECONDARY=false

#       To we append FASTA/Q comments to SAM files?
APPEND=false

#       Do we use hard clipping?
HARD=false

#       Do we mark split hits as secondary?
SPLIT=true

#       What is the verbosity level?
#           Choose from:
#               'disabled', 'errors'
#               'warnings', 'all', or' debug'
VERBOSITY='all'

############################################
##########     SAM_Processing     ##########
############################################

#   Where is the list of read-mapped samples?
MAPPED_SAMPLES=

############################################
##########     Coverage_Map       ##########
############################################

#   Where is the list of processed BAM samples?
BAM_SAMPLES=

#   Where is the reference annotaiton file (GFF or BED)?
REF_ANN=

############################################
##########     Plot_Coverage      ##########
############################################

#   Where is the list of text coverage histograms?
HIST_SAMPLES=

############################################
##########      Dependencies      ##########
############################################

#   This section defines installations to
#       various dependencies for sequence_handling
#   If you are able to use a module system for
#       dependencies, then uncomment the lines starting
#       with 'module load'
#   If you need to install a dependency from source,
#       then uncomment the lines for the depency and the
#       'export PATH=', and write the full path to the executable
#       for the program. For example:
#       PARALLEL=${HOME}/software/parallel-20151122/bin/parallel
#   If you have a system-wide installation for a program, you can
#       leave all lines commented out. sequence_handling will find
#       system-wide installed programs automatically.

#   Do we have GNU parallel installed
#module load parallel 2> /dev/null
#PARALLEL=
#export PATH=${PATH}:${PARALLEL}

#   Do we have Bioawk installed?
#BIOAWK=
#export PATH=${PATH}:${BIOAWK}

#   Do we have FastQC installed?
#module load FastQC 2> /dev/null
#FASTQC=
#export PATH=${PATH}:${FASTQC}

#   Do we have Seqqs installed?
#SEQQS=
#export PATH=${PATH}:${SEQQS}

#   Do we have Sickle installed?
#SICKLE=
#export PATH=${PATH}:${SICKLE}

#   Do we have Scythe installed?
#SCYTHE=
#export PATH=${PATH}:${SCYTHE}

#   Do we have R installed?
#module load R 2> /dev/null
#R=
#export PATH=${PATH}:${R}

#   Do we have BWA installed?
#module load BWA 2> /dev/null
#BWA=
#export PATH=${PATH}:${BWA}

#   Do we have SAMTools installed?
#module load samtools 2> /dev/null
#SAMTOOLS=
#export PATH=${PATH}:${SAMTOOLS}

#   Do we have BEDTools installed?
#module load bedtools 2> /dev/null
#BEDTOOLS=
#export PATH=${PATH}:${BEDTOOLS}
