#!/bin/bash

#   What is the sample list of raw samples?
RAW_SAMPLES=

#   Where are we storing the output files?
#       Final directory is ${OUT_DIR}/Name_of_Handler
OUT_DIR=

#   Name this project
PROJECT=

#   What email should we use for job notifications?
EMAIL=user@example.com

#   What is the platform used for sequencing?
#       Look at the FastQC files to determine
#       the sequencing platform. Choose from:
#           'sanger', 'illumina'
#           'solexa', or 'phred'
PLATFORM=

#   What reference genome are we using?
REF_GEN=

#   Where is the list of processed BAM samples?
#       This is used for Coverage_Map and Indel_Realignment
#       If using SAM_Processing, then leave as is
BAM_SAMPLES=${OUT_DIR}/SAM_Processing/${PROJECT}_Processed_BAM.txt

############################################
##########   Quality_Assessment   ##########
############################################

#   What are our QSub settings for Quality_Assessment?
#       Below are the recommended settings
QA_QSUB="mem=4000mb,nodes=1:ppn=4,walltime=6:00:00"

############################################
##########     Read_Depths        ##########
############################################

#   What are our QSub settings for Read_Depths?
#       Below are the recommended settings
RD_QSUB="mem=4000mb,nodes=1:ppn=4,walltime=6:00:00"

#   Where is the list of FastQC zipfiles?
ZIP_FILES=${OUT_DIR}/Quality_Assessment/${PROJECT}_FastQC_ZipFiles.txt

#   What is the target size, or size of the genome/region that was sequenced?
TARGET=

############################################
##########     Adapter_Trimming   ##########
############################################

#   What are our QSub settings for Adapter_Trimming?
#       Below are the recommended settings
AT_QSUB="mem=1gb,nodes=1:ppn=8,walltime=10:00:00"

#   How are forward samples named?
#       Example: _1_sequence.txt.gz
FORWARD_NAMING=

#   How are reverse samples named?
#       Example: _2_sequence.txt.gz
REVERSE_NAMING=

#   If you have single-end samples, leave
#       FORWARD_NAMING and REVERSE_NAMING blank

#	What is our adapter file?
ADAPTERS=

#   What is Scythe's prior contamination rate?
#       REcommended: 0.05
PRIOR=

############################################
##########     Quality_Trimming   ##########
############################################

#   What are our QSub settings for Quality_Trimming?
#       Below are the recommended settings
QT_QSUB="mem=1gb,nodes=1:ppn=8,walltime=10:00:00"

#   Where is our list of trimmed samples?
ADAPTED_LIST=${OUT_DIR}/Adapter_Trimming/${PROJECT}_trimmed_adapters.txt

#   How are trimmed forward samples named?
#       If using the Adapter_Trimming handler,
#       leave the following definition as is
FORWARD_ADAPTED=_Forward_ScytheTrimmed.fastq.gz

#   How are trimmed reverse samples named?
#       If using the Adapter_Trimming handler,
#       leave the following definition as is
REVERSE_ADAPTED=_Reverse_ScytheTrimmed.fastq.gz

#   If using single-end samples, leave
#       FORWARD_ADAPTED and REVERSE_ADAPTED blank

#   How are trimmed single samples named?
#       If using the Adapter_Trimming handler,
#       leave the following definition as is
SINGLES_ADAPTED=_Single_ScytheTrimmed.fastq.gz

#   What is the threshold for trimming?
#       Normal trimming: use 20
THRESHOLD=

############################################
##########  	Read_Mapping	  ##########
############################################

#   What are our QSub settings for Read_Mapping?
#       Below are the recommended settings
RM_QSUB="mem=8gb,nodes=1:ppn=8,walltime=16:00:00"

#   Where is our list of trimmed samples?
#       If you're using the list from Adapter_Trimming
#       TRIMMED_LIST=${OUT_DIR}/Adapter_Trimming/${PROJECT}_trimmed_adapters.txt
#       If you're using the list from Quality_Trimming
#       TRIMMED_LIST=${OUT_DIR}/Quality_Trimming/${PROJECT}_trimmed_quality.txt
TRIMMED_LIST=

#   How are trimmed forward samples named?
#       If using the Adapter_Trimming handler
#       FORWARD_TRIMMED=_Forward_ScytheTrimmed.fastq.gz
#       If using the Quality_Trimming handler
#       FORWARD_TRIMMED=_R1_trimmed.fastq.gz
FORWARD_TRIMMED=

#   How are trimmed reverse samples named?
#       If using the Adapter_Trimming handler
#       REVERSE_TRIMMED=_Reverse_ScytheTrimmed.fastq.gz
#       If using the Quality_Trimming handler
#       REVERSE_TRIMMED=_R2_trimmed.fastq.gz
FORWARD_TRIMMED=

#   How are trimmed single-end samples named?
#       If using the Adapter_Trimming handler
#       SINGLES_TRIMMED=_Single_ScytheTrimmed.fastq.gz
#       If using the Quality_Trimming handler
#       SINGLES_TRIMMED=_single_trimmed.fastq.gz
SINGLES_TRIMMED=

#   BWA mem parameters; below are the defaults for BWA mem
#       How many threads are we using?
THREADS=1

#       What is our minimum seed length?
SEED=19

#       What is the band width?
WIDTH=100

#       What is our off-diagonal x-dropoff (Z-dropoff)?
DROPOFF=100

#       What is our re-seed value?
RE_SEED=1.5

#       What is our cutoff value?
CUTOFF=10000

#       What is our matching score?
MATCH=1

#       What is our mismatch penalty?
MISMATCH=4

#       What is our gap penalty?
GAP=6

#       What is our gap extension penalty?
EXTENSION=1

#       What is our clipping penalty?
CLIP=6

#       What is our unpaired read penatly?
UNPAIRED=9

#       Do we assume the first input query is interleaved?
INTERLEAVED=false

#       What is our minimum threshold?
THRESHOLD=30

#       Do we output all alignments, and mark as secondary?
SECONDARY=false

#       Do we append FASTA/Q comments to SAM files?
APPEND=false

#       Do we use hard clipping?
HARD=false

#       Do we mark split hits as secondary?
SPLIT=true

#       What is the verbosity level?
#           Choose from:
#               'disabled', 'errors'
#               'warnings', 'all', or 'debug'
VERBOSITY='all'

############################################
##########     SAM_Processing     ##########
############################################

#   Specify how you would like your SAM files to be processed
#       Choose from:
#           'picard' (recommended) or 'samtools'
METHOD=

#   What are our QSub settings for SAM_Processing?
#       Below are the recommended settings
SP_QSUB="mem=12gb,nodes=1:ppn=8,walltime=24:00:00"

#   Where are the read-mapped samples located?
#       If using Read_Mapping, leave as is
MAPPED_DIRECTORY="${OUT_DIR}/Read_Mapping"

#   The next four variables are only used if processing with Picard

#   What is the full file path for the Picard jar file?
PICARD_JAR=

#   What is the most amount of memory that we can use?
#       Please stylize as #g: ex 15g
MAX_MEM=

#   What is the maximum number of file handles that we can use?
#       For UNIX systems, the per-process maximum number of files 
#           that can be open may be found with 'ulimit -n'
#       We recommend setting MAX_FILES to be slightly under this value
MAX_FILES=

#   Where should Picard store temporary files?
#       If you've encountered issues with running out of temp space
#           with picard, you can optionally specify a temp directory
#       Otherwise, leave blank
TMP=

############################################
##########   Coverage_Mapping     ##########
############################################

#   What are our Qsub settings for Coverage_Mapping?
#       Below are the recommended settings
CM_QSUB="mem=12gb,nodes=1:ppn=8,walltime=24:00:00"

#   Where is the reference annotaiton file (GFF or BED)?
REF_ANN=

############################################
##########   Indel_Realignment    ##########
############################################

#   What are our Qsub settings for Indel_Realignment?
#       Below are the recommended settings
IR_QSUB="mem=15gb,nodes=1:ppn=4,walltime=48:00:00"

#   What is the full file path for the GATK jar file?
GATK_JAR=

#   What is the most amount of memory we can use for GATK?
#       We suggest no less than 4 GB
#       Please stylize as #g: ex 4g
MAX_MEMORY=4g

#   What model are we using for indel realignment?
#       Choose from:
#           'KNOWNS_ONLY', 'USE_READS'
#           or 'USE_SW'
#       Below is the default
MODEL=KNOWNS_ONLY

#   What log of odds score should we use?
#       Below is the default
LOG_ODDS=0.4

#   Where is the VCF file describing known indels?
KNOWN_INDELS=

#   What are our target intervals?
#       If not generated, leave blanl and we will generate for you
#       Be sure to increase the walltime in IR_QSUB to allow for the creation
TARGET_INTERVALS=

############################################
##########      Dependencies      ##########
############################################

#   This section defines installations to
#       various dependencies for sequence_handling
#   If you are able to use a module system for
#       dependencies, then uncomment the lines starting
#       with 'module load'
#   If you need to install a dependency from source,
#       then uncomment the lines for the depency and the
#       'export PATH=', and write the full path to the executable
#       for the program. For example:
#       PARALLEL=${HOME}/software/parallel-20151122/bin/parallel
#   If you have a system-wide installation for a program, you can
#       leave all lines commented out. sequence_handling will find
#       system-wide installed programs automatically.

#   Do we have GNU parallel installed
#module load parallel
#PARALLEL=
#export PATH=${PARALLEL}:${PATH}

#  Do we have Bioawk installed?
#BIOAWK=
#export PATH=${BIOAWK}:${PATH}

#   Do we have FastQC installed?
#module load fastqc
#FASTQC=
#export PATH=${FASTQC}:${PATH}

#   Do we have Seqqs installed?
#SEQQS=
#export PATH=${SEQQS}:${PATH}

#   Do we have Sickle installed?
#SICKLE=
#export PATH=${SICKLE}:${PATH}

#   Do we have Scythe installed?
#SCYTHE=
#export PATH=${SCYTHE}:${PATH}

#   Do we have R installed?
#module load R
#R=
#export PATH=${R}:${PATH}

#   Do we have BWA installed?
#module load bwa
#BWA=
#export PATH=${BWA}:${PATH}

#   Do we have SAMTools installed?
#module load samtools
#SAMTOOLS=
#export PATH=${SAMTOOLS}:${PATH}

#   Do we have BEDTools installed?
#module load bedtools
#BEDTOOLS=
#export PATH=${BEDTOOLS}:${PATH}

#   Do we have Java installed?
#module load java
#JAVA=
#export PATH=${JAVA}:${PATH}