#!/bin/bash

#   This Config file is intended to be used with Oxford Nanopore sequencing data

#   Where are we storing the output files?
#       Final directory is ${OUT_DIR}/Name_of_Handler
OUT_DIR=

#   Name this project
PROJECT=

#   What email should we use for job notifications?
EMAIL=

#   Provide the full file path to the reference genome fasta file
REF_GEN=

############################################
##########   Quality_Assessment   ##########
############################################

#   What are our QSub settings for Quality_Assessment?
QA_QSUB="mem=1gb,nodes=1:ppn=4,walltime=24:00:00"

#   Provide the full file path to a list of the fastq files to be assessed
QA_SAMPLE_LIST=

############################################
##########    Adapter_Trimming    ##########
############################################

#   What are our QSub settings for Adapter_Trimming?
AT_QSUB="mem=1gb,nodes=1:ppn=4,walltime=2:00:00"

#   Provide the full file path to a list of files to be trimmed
#       Accepts uncompressed or gzipped fasta and fastq files
AT_SAMPLE_LIST=

############################################
##########      Read_Mapping      ##########
############################################

#   What are our QSub settings for Read_Mapping?
RM_QSUB="mem=1gb,nodes=1:ppn=4,walltime=24:00:00"

#   Provide a .mmi index for your reference file
REFERENCE_MINIMAP_INDEX=

#   Provide the full file path to a list of files to be mapped
#       Accepts uncompressed or gzipped fasta and fastq files
RM_SAMPLE_LIST=

#   What file type should be outputted? 
#       Choose from: "SAM" or "PAF"
OUTPUT_FORMAT="SAM"

#   For more information on the following parameters do
#       minimap2 -h
BANDWIDTH=500
MATCHING_SCORE=2
MISMATCH_PENALTY=4
GAP_OPEN_PENALTY=4,24
GAP_EXTENSION_PENALTY=2,1
Z_DROP_SCORE=400,200
MINIMAL_PEAK_DP_SCORE=80
THREADS=4

############################################
##########     SAM_Processing     ##########
############################################

#   What are our QSub settings for SAM_Processing?
#       Below are the recommended settings
SP_QSUB="mem=22gb,nodes=1:ppn=16,walltime=24:00:00"

#   Where is the list of read-mapped samples?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/HelperScripts/sample_list_generator.sh
SP_SAMPLE_LIST=

############################################
##########      Dependencies      ##########
############################################

#   Please visit https://github.com/MorrellLab/sequence_handling/wiki/Dependencies
#       for information on version requirements and compatibility

#   Also requires Poretools and Porechop

#   Do we have python 2 installed?
module load python3_ML/2.7.13
#PYTHON2=
#export PATH=${PYTHON2}:${PATH}

#   Do we have python 3 installed?
module load python3_ML/3.6.4
#PYTHON3=
#export PATH=${PYTHON3}:${PATH}

#   Do we have minimap2 installed?
module load minimap2_ML/2.9.0
#MINIMAP2=
#export PATH=${MINIMAP2}:${PATH}

#   Do we have SAMTools installed?
module load samtools_ML/1.3.1
#SAMTOOLS=
#export PATH=${SAMTOOLS}:${PATH}
