#!/bin/bash

# This script is for submitting a job to Slurm via sbatch

set -e
set -o pipefail

# Required input arguments
CONFIG=$1
SEQUENCE_HANDLING=$2

source ${CONFIG}
source ${SEQUENCE_HANDLING}/Handlers/Adapter_Trimming.sh
# Call on function
# Variables below are stored in CONFIG
Adapter_Trimming ${RAW_SAMPLES} ${OUT_DIR} ${PROJECT} ${FORWARD_NAMING} ${REVERSE_NAMING} ${ADAPTERS} ${PRIOR} ${QUAL_ENCODING}
