#!/bin/bash

# This script is for submitting a job to Slurm via sbatch

set -e
set -o pipefail

# Required input arguments
CONFIG=$1
SEQUENCE_HANDLING=$2
IR_MEM=$3
gatkVer=$4

source ${CONFIG}
source ${SEQUENCE_HANDLING}/Handlers/Indel_Realigner.sh
# Call on function
# Variables below are stored in CONFIG
Indel_Realigner ${IR_BAM_LIST} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${IR_MEM} ${IR_TARGETS} ${LOD_THRESHOLD} ${ENTROPY_THRESHOLD} ${FIX_QUALITY_SCORES} ${gatkVer} ${MAX_READS_IN_MEM}
