#!/bin/bash

set -euo pipefail

CONFIG="$1"
SEQUENCE_HANDLING="$2"

source "${CONFIG}"
source "${SEQUENCE_HANDLING}/Handlers/Octopus_Variant_Calling.sh"

Octopus_Variant_Calling \
    "${OCTOPUS_BAM_LIST}" \
    "${OUT_DIR}" \
    "${OCTOPUS_COHORT_NAME}" \
    "${REF_GEN}" \
    "${OCTOPUS_ERROR_MODEL}" \
    "${OCTOPUS_CALLING_MODEL}" \
    "${PLOIDY}" \
    "${OCTOPUS_THREADS}" \
    "${OCTOPUS_MATERNAL_SAMPLE:-}" \
    "${OCTOPUS_PATERNAL_SAMPLE:-}" \
    "${OCTOPUS_CALLABLE_REGIONS:-}"