#!/bin/bash

# This script is for submitting a job to Slurm via sbatch

set -e
set -o pipefail

# Required input arguments
CONFIG=$1
SEQUENCE_HANDLING=$2

source ${CONFIG}
source ${SEQUENCE_HANDLING}/Handlers/Pre_Variant_Filtering.sh
# Call on function
# Variables below are stored in CONFIG
Pre_Variant_Filtering_GATK4 ${PVF_VCF} ${OUT_DIR} ${REF_GEN} ${PROJECT} ${SEQUENCE_HANDLING} ${PVF_GEN_NUM} ${PVF_GEN_LEN} ${TMP}
