#!/bin/bash

# This script is for submitting a job to Slurm via sbatch

set -e
set -o pipefail

# Required input arguments
CONFIG=$1
SEQUENCE_HANDLING=$2
MODE=$3

source ${CONFIG}
source ${SEQUENCE_HANDLING}/Handlers/Read_Mapping.sh
# Call on function
# Variables below are stored in CONFIG
Read_Mapping ${TRIMMED_LIST} ${SINGLES_TRIMMED} ${FORWARD_TRIMMED} ${REVERSE_TRIMMED} ${MODE} ${PROJECT} ${SEQ_PLATFORM} ${OUT_DIR} ${REF_GEN}
