#!/bin/bash

# This script is for submitting a job to Slurm via sbatch

set -e
set -o pipefail

# Required input arguments
CONFIG=$1
SEQUENCE_HANDLING=$2
RTC_MEM=$3
gatkVer=$4

source ${CONFIG}
source ${SEQUENCE_HANDLING}/Handlers/Realigner_Target_Creator.sh
# Call on function
# Variables below are stored in CONFIG
Realigner_Target_Creator ${RTC_BAM_LIST} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${RTC_MEM} ${FIX_QUALITY_SCORES} ${gatkVer}
